#!/usr/bin/env python3
"""
Update ONLY the alignmentRationale field for all ISO 42001 questions
Preserves existing citation and controlIntent fields
"""

import json

# Complete updated rationale content from Excel v6
updated_rationales = {
    "FA-1": "This question requires the organisation to put concrete mechanisms in place to detect and mitigate bias across the AI lifecycle. ISO/IEC 42001 expects organisations that define fairness as an objective to embed measures addressing bias within requirements definition, data handling, model training, evaluation and validation. Because the question directly targets these lifecycle-integrated bias-management practices, it fully aligns with the control's expectations.",
    
    "FA-2": "This question asks how the organisation checks that training data covers relevant demographic groups and avoids systematic exclusion or disadvantage. ISO/IEC 42001 requires assessment and documentation of impacts on individuals and groups and directs organisations to consider demographic representation when analysing fairness. Since demographic coverage in training data is fundamental to these required impact assessments, the question fully aligns with the control.",
    
    "FA-3": "This question requires organisations to examine AI system outputs for unequal outcomes across different user groups. ISO/IEC 42001 instructs organisations to evaluate AI systems against fairness-related criteria and to assess impacts on individuals and groups. Because identifying disparities in outcomes is central to determining whether fairness objectives are being met, the question fully aligns with the control's evaluation requirements.",
    
    "FA-4": "This question asks the organisation to define fairness in measurable terms and to use explicit criteria or metrics to evaluate outputs. ISO/IEC 42001 requires responsible-AI objectives such as fairness to be defined and operationalised through documented criteria and for AI systems to be evaluated against those criteria, with deficiencies addressed. As the question directly targets the establishment and use of fairness metrics, it fully aligns with the control.",
    
    "FA-5": "This question requires the organisation to test for fairness and bias under realistic operating conditions rather than only in controlled development environments. ISO/IEC 42001 requires assessment of consequences of AI system behaviour across contexts of use, including predictable failures and differing impacts on individuals and groups. Real-world fairness evaluation directly supports these expectations, so the question fully aligns with the control.",
    
    "FA-6": "This question focuses on the use of specific tools or frameworks to assess and mitigate bias. ISO/IEC 42001 requires that appropriate testing tools or methods be integrated into the development lifecycle where fairness is an objective but remains agnostic about which tools are used. Because the question emphasises a particular implementation (named tools) rather than the broader requirement to embed fairness measures throughout the lifecycle, the alignment is partial.",
    
    "FA-7": "This question asks whether fairness protections are explicitly extended to minority or underserved groups. ISO/IEC 42001 requires assessment of AI system impacts on different groups, including those with specific protection needs, as part of fairness and accessibility objectives. Since the question directly targets group-specific fairness considerations that the standard highlights, it fully aligns with the control.",
    
    "FA-8": "This question checks whether fairness is built into design and development processes rather than treated as a reactive, post-deployment concern. ISO/IEC 42001 requires fairness objectives to be incorporated into design and development processes and for measures supporting those objectives to be integrated across the lifecycle. Because the question explicitly distinguishes proactive integration from purely reactive approaches, it fully aligns with the control.",
    
    "TR-1": "This question requires the organisation to describe how clearly and comprehensively it communicates what the AI system does, how it works and where its limitations lie. ISO/IEC 42001 requires organisations to determine and provide necessary information so that users and stakeholders understand when they are interacting with an AI system, its intended purpose, potential harms or benefits, limitations and operational requirements. Because the question directly tests whether this information is being communicated at an appropriate level of detail, it fully aligns with the control.",
    
    "TR-2": "This question asks whether the organisation systematically documents data sources, algorithms and lifecycle processes to support accountability and auditability. ISO/IEC 42001 requires documentation of AI system design and development, verification and validation measures, deployment, operation and monitoring, and it mandates defined data management processes including acquisition, selection, quality requirements and provenance. As the question focuses on the same structured documentation, it fully aligns with the control.",
    
    "TR-3": "This question evaluates whether external stakeholders such as regulators and customers are given sufficient information or tools to understand the AI system. ISO/IEC 42001 requires organisations to provide appropriate technical documentation and information to different categories of interested parties and to establish capabilities for interested parties to report adverse impacts. Because the question assesses whether such outward-facing transparency mechanisms exist, it fully aligns with the control.",
    
    "TR-4": "This question asks about structured internal and external communication processes for AI-related information. ISO/IEC 42001 requires organisations to determine internal and external communications relevant to the AI management system, including what will be communicated, when, to whom and how, and to ensure that users and other interested parties receive necessary information about the AI system. As the question directly probes these communication arrangements, it fully aligns with the control.",
    
    "TR-5": "This question focuses on identifying opaque, hard-to-explain components and on recognising their impact on transparency. ISO/IEC 42001 acknowledges that some AI systems can lack transparency or explainability and notes that such characteristics may require additional safeguards, but it does not mandate eliminating black-box models or fully resolving opacity. Because the question surfaces a specific transparency concern without being directly required by the control, and the standard addresses this only at a risk-management level, the alignment is partial.",
    
    "TR-6": "This question requires the organisation to explain how it discloses data sources and algorithmic choices, including relevant limitations and provenance, to stakeholders. ISO/IEC 42001 requires defined and documented processes for data management and provenance and states that technical documentation can include information about data sets used for training, validation and testing, as well as algorithmic choices and justification. Because the question checks whether this type of information is actually disclosed, it fully aligns with the control.",
    
    "TR-7": "This question asks whether users are clearly informed that they are interacting with an AI system rather than a human. ISO/IEC 42001 guidance on information for users emphasises that users must understand when they are interacting with an AI system and lists this as an example of information that should be provided. As the question matches this requirement directly, it fully aligns with the control.",
    
    "TR-8": "This question evaluates whether the organisation produces regular transparency reports or equivalent documentation for regulators and customers. ISO/IEC 42001 requires organisations to provide capabilities for interested parties to report adverse impacts, to plan communication of incidents and to determine and document obligations to report information about the AI system to interested parties, including regulators and customers. It also notes that shared information can include technical documentation, risks, impact assessment results and logs. Because the question specifically probes such reporting practices, it fully aligns with the control.",
    
    "EX-1": "This question requires the organisation to determine explainability expectations based on context, stakeholders and potential impacts. ISO/IEC 42001 requires organisations to identify and document objectives for responsible use of AI systems, explicitly including explainability, and to implement mechanisms to achieve those objectives. Annex guidance further links explainability needs to stakeholder information requirements and risk. Because the question asks how this calibration is done in practice, it fully aligns with the control.",
    
    "EX-2": "This question focuses on whether explanations are tested with users to verify that they can interpret them correctly. ISO/IEC 42001 requires evaluation plans to include methods, guidance or metrics to assess whether relevant interested parties who make or are subject to decisions based on AI outputs can adequately interpret those outputs. As the question operationalises this requirement by asking how such testing is carried out, it fully aligns with the control.",
    
    "EX-3": "This question asks whether explanation content and format are tailored to different audiences such as end-users, regulators or technical teams. ISO/IEC 42001 requires organisations to determine what information and technical documentation are needed for each category of interested party and to provide it in appropriate form, and it defines explainability as providing understandable explanations of important factors influencing AI results. Because the question checks whether explanation formats are adapted to audience needs, it fully aligns with the control, although the mapping is somewhat interpretive.",
    
    "EX-4": "This question requires the organisation to assess whether explanations faithfully reflect the system's decision logic and include all relevant factors. ISO/IEC 42001 requires evaluation plans to include methods and metrics to assess whether interested parties can adequately interpret AI outputs and calls for AI systems to be evaluated against documented criteria, with evaluation methodologies improving completeness and reliability of performance assessment. As the question directly targets evaluation of explanation quality against such criteria, it fully aligns with the control.",
    
    "EX-5": "This question explores how the organisation balances model performance against explainability when choosing model architectures. ISO/IEC 42001 recognises lack of transparency or explainability as an AI-specific concern that can affect trustworthiness and accountability and notes that such risks require appropriate safeguards, but it does not prescribe explicit trade-off or decision processes between complexity and explainability. Because the question focuses on a design trade-off that is implied but not explicitly required by the standard, the alignment is partial.",
    
    "EX-6": "This question requires the organisation to design the system and supporting materials so that users can understand why particular outputs or decisions were produced. ISO/IEC 42001 requires providing necessary information to users so they understand how the AI system works, its purpose, potential harms and benefits, limitations and operational requirements, and it calls for evaluation methods to determine whether interested parties can adequately interpret AI outputs. Because the question directly examines how interpretability for users is achieved, it fully aligns with the control.",
    
    "EX-7": "This question focuses on specific tools and techniques used to increase model explainability. ISO/IEC 42001 requires organisations to define explainability as an objective where relevant and to integrate measures into the development lifecycle to achieve such objectives, noting that measures can include requirements to use specific tools or methods. However, the standard does not mandate particular tools such as SHAP or LIME. Because the question addresses one tool-based implementation of a more general requirement, the alignment is partial.",
    
    "EX-8": "This question asks whether explanations are tailored to the needs of different stakeholder groups such as end-users, regulators and internal teams. ISO/IEC 42001 requires organisations to determine what technical documentation and information are needed for each relevant category of interested party and to provide it appropriately, and it defines explainability as providing understandable explanations to interested parties. As the question directly tests whether explanations are differentiated by group, it fully aligns with the control.",
    
    "AC-1": "This question requires the organisation to define responsibilities, processes and documentation for managing AI system failures and ensuring accountability when things go wrong. ISO/IEC 42001 requires roles and responsibilities for AI systems to be defined and allocated and calls for documentation of operation and monitoring, including handling repairs, failures and updates, as well as plans for managing failures and notifying users. Because the question addresses these structured accountability arrangements, it fully aligns with the control.",
    
    "AC-2": "This question asks whether formal governance mechanisms, such as oversight boards or committees, are in place to oversee AI systems and their outcomes. ISO/IEC 42001 requires establishing accountability within the organisation for implementing, operating and managing AI systems, defines AI-related roles and responsibilities and expects top management to assign and communicate relevant authorities. These requirements support formal oversight structures, so the question fully aligns with the control.",
    
    "AC-3": "This question focuses on whether there are defined escalation policies and processes when significant AI-related issues or concerns are identified. ISO/IEC 42001 requires processes for reporting concerns about the organisation's role with respect to AI systems and guidance that reporting mechanisms should allow escalation to management and protect reporters. It also requires documented plans for communicating incidents to users and determining which incidents must be communicated. Because the question directly targets these escalation arrangements, it fully aligns with the control.",
    
    "AC-4": "This question asks about structured mechanisms for handling and resolving customer complaints or disputes about AI decisions, potentially including appeals and human review. ISO/IEC 42001 requires processes for interested parties to report concerns or adverse impacts and for organisations to determine obligations to report information about AI systems and communicate incidents. While these requirements support receiving and responding to complaints, they do not explicitly mandate detailed dispute-resolution workflows or appeal rights. As a result, the alignment is partial.",
    
    "AC-5": "This question examines whether AI governance roles and responsibilities are clearly defined, documented and communicated across technical, legal and operational teams. ISO/IEC 42001 requires roles and responsibilities for AI to be defined and allocated, calls for responsibilities to be specified to a level that enables individuals to perform their duties, and requires top management to ensure that responsibilities and authorities are assigned and communicated. It also expects responsibilities across the AI system lifecycle to be documented between the organisation and external parties. Because the question directly reflects these expectations, it fully aligns with the control.",
    
    "AC-6": "This question requires the organisation to designate accountable owners for monitoring and managing the AI system from development through deployment and operation. ISO/IEC 42001 requires documentation of operational elements such as system and performance monitoring, repairs, updates and support, and guidance on documenting roles responsible for system health, failure handling and updates, including in collaboration with third parties. As the question directly probes lifecycle ownership and accountability, it fully aligns with the control.",
    
    "AC-7": "This question asks whether event logs or audit trails are maintained to document AI system behaviour and support traceability of decisions. ISO/IEC 42001 requires organisations to determine at which phases of the AI system lifecycle record keeping of event logs should be enabled and explains that logs should capture information such as time and date of use, production data and outputs outside intended operation. Because the question focuses on maintaining such traceable records, it fully aligns with the control.",
    
    "AC-8": "This question focuses on mechanisms for addressing disputes or concerns about AI outcomes, such as appeal processes or review channels. ISO/IEC 42001 requires organisations to establish processes for reporting concerns and adverse impacts and to determine obligations for communicating information about AI systems and incidents to interested parties. While this supports receiving, investigating and communicating about concerns, it does not explicitly require comprehensive dispute-resolution or appeal mechanisms for individual decisions, so the alignment is partial.",
    
    "DI-1": "This question requires the organisation to define, measure and maintain data accuracy, completeness and quality for data used in AI training, validation and production. ISO/IEC 42001 requires definition of data-quality requirements and ensures that data used to develop and operate AI systems meet those requirements, emphasising that the quality of training, validation, test and production data should be defined, measured and improved. Because the question directly addresses these practices, it fully aligns with the control.",
    
    "DI-2": "This question focuses on tracking data origin, movement and transformation over time, including recording updates and changes. ISO/IEC 42001 requires organisations to define and document processes for recording data provenance over the life cycles of both the data and the AI system and specifies that data documentation should include provenance and dates of last update or modification. As the question explicitly probes these lineage and change-tracking processes, it fully aligns with the control.",
    
    "DI-3": "This question asks whether formal governance policies govern how data are collected, used, retained and disposed of across the AI lifecycle. ISO/IEC 42001 requires defined, documented and implemented data management processes, including acquisition and selection of data, and states that data documentation should include categories of data, intended use, applicable retention and disposal policies and quality requirements. Because the question targets these governance aspects explicitly, it fully aligns with the control.",
    
    "DI-4": "This question requires the organisation to maintain data currency and accuracy over time through updates and validation. ISO/IEC 42001 requires that data-quality requirements be defined and met and that the quality of training, validation, test and production data be measured and improved, and it specifies that data documentation should record the date of last update or modification. These provisions support mechanisms for maintaining up-to-date and accurate data, so the question fully aligns with the control.",
    
    "DI-5": "This question examines how the organisation detects and remediates missing or incomplete data, for example through cleaning, imputation or other preparation techniques. ISO/IEC 42001 requires definition of criteria for data preparation and methods used and explains that data preparation often includes dealing with missing entries and applying imputation or other transformations. Because the question directly concerns such structured handling of missing data, it fully aligns with the control.",
    
    "DI-6": "This question asks about the organisation's approach to data preprocessing, including cleaning, normalisation and other transformations before model training or inference. ISO/IEC 42001 requires organisations to define and document criteria and methods for data preparation, notes that poor preparation can lead to AI system errors and lists typical preparation methods such as cleaning, imputation, normalisation and scaling. Since the question probes these structured preprocessing practices, it fully aligns with the control.",
    
    "DI-7": "This question focuses on whether external or third-party data sources are systematically assessed for quality and reliability before use in AI systems. ISO/IEC 42001 requires documenting acquisition and selection of data, including types and characteristics of data sources (internal, purchased, shared, open, synthetic) and associated metadata such as provenance, and it requires that data used meet defined quality requirements. Because the question targets evaluation of external data sources against such criteria, it fully aligns with the control.",
    
    "DI-8": "This question asks how the organisation ensures end-to-end traceability of data across the AI lifecycle, including where data came from, how it was transformed and how it was used. ISO/IEC 42001 requires defined and documented processes for recording data provenance covering creation, updates, transformations and sharing, and it notes that event logs can record production data to support traceability of functionality. As the question directly examines these lineage and traceability practices, it fully aligns with the control.",
    
    "RE-1": "This question requires the organisation to test the AI system across a range of conditions, including challenging scenarios, to confirm that performance is consistently within expected bounds. ISO/IEC 42001 requires definition of verification and validation measures, establishment of evaluation criteria and specification of performance-assessment methodologies (including metrics, data selection and conditions of use) to ensure reliable performance assessment. Because the question targets systematic testing under varying conditions, it fully aligns with the control.",
    
    "RE-2": "This question focuses on whether stress tests or simulations are used to probe system behaviour under extreme or unusual conditions. ISO/IEC 42001 requires verification and validation measures and states that evaluation plans should consider reliability and safety requirements, acceptable error rates and operational factors, and may involve introducing erroneous or spurious data to see how performance is affected. While this supports robustness testing conceptually, the standard does not explicitly require formal stress tests or simulations, so the alignment is partial.",
    
    "RE-3": "This question asks about continuous monitoring mechanisms to detect performance degradation, such as model or data drift, and to trigger corrective actions. ISO/IEC 42001 requires definition of elements for ongoing operation, including system and performance monitoring, repairs, updates and support, and guidance that monitoring should confirm that the system behaves as expected on production data and detect changes such as drift that may require retraining. Because the question directly addresses these monitoring practices, it fully aligns with the control.",
    
    "RE-4": "This question requires the organisation to define clear, measurable reliability metrics and use them to evaluate system performance. ISO/IEC 42001 requires definition of verification and validation measures, specification of criteria for their use and inclusion of reliability and safety requirements, acceptable error rates and evaluation metrics in the evaluation criteria. Since the question focuses on defining and using such reliability metrics, it fully aligns with the control.",
    
    "RE-5": "This question asks whether the organisation has proactively identified where and how the AI system might fail to inform safeguards and contingency plans. ISO/IEC 42001 requires planning for operation and monitoring, including processes to respond to and repair errors and failures, and it expects technical documentation to include plans for managing failures. However, it does not explicitly require a structured analysis of potential failure points in advance. As a result, the alignment is partial.",
    
    "RE-6": "This question focuses on ensuring that the system performs reliably under varying or unusual conditions, including edge cases. ISO/IEC 42001 requires evaluation criteria that consider reliability and safety requirements, acceptable error rates and operational conditions of use and suggests that performance-assessment methodologies reflect operational attributes, potentially including degraded or erroneous inputs. While this supports assessing behaviour under varied conditions, the standard does not explicitly require targeted edge-case testing, so the alignment is partial.",
    
    "RE-7": "This question requires mechanisms to detect downtime and errors and restore normal operation promptly. ISO/IEC 42001 requires definition of elements for ongoing operation including system and performance monitoring, repairs, updates and support, and its guidance emphasises monitoring for errors and failures and having processes for response and repair. The standard also calls for capabilities that allow users and external parties to report adverse impacts. Because the question focuses on these detection and recovery mechanisms, it fully aligns with the control.",
    
    "RE-8": "This question asks whether the organisation has defined frequencies and processes for retesting and retraining models to maintain reliability over time. ISO/IEC 42001 requires elements for ongoing operation and monitoring, explains that performance must be monitored especially for systems that learn on production data and notes that concept or data drift can require retraining. It also states that evaluation frequency should be determined. As the question directly addresses how often such testing and retraining occur, it fully aligns with the control.",
    
    "SE-1": "This question asks about concrete safeguards such as access controls, encryption and tamper protection for AI models and data. ISO/IEC 42001 requires organisations to identify AI-specific information security threats across the AI lifecycle, including data poisoning, model stealing and model inversion, and to manage these risks as part of trustworthiness. However, it does not prescribe specific mechanisms like particular access-control patterns or tamper-proof storage. Because the question focuses on implementation details that are consistent with, but not explicitly required by, the standard, the alignment is partial.",
    
    "SE-2": "This question examines how the organisation identifies and mitigates adversarial attacks designed to manipulate model outputs. ISO/IEC 42001 requires identification and management of AI-specific security threats, including data poisoning and other attacks that affect model behaviour, and expects security considerations to be integrated into design and development. It does not, however, mandate specific adversarial training or detection techniques. As a result, the question is consistent with the risk-management intent but only partially aligned with explicit requirements.",
    
    "SE-3": "This question asks about periodic security audits and penetration tests focused on AI systems. ISO/IEC 42001 requires organisations to manage security concerns throughout the AI lifecycle and to define testing, verification and release criteria, but it does not specifically require penetration testing or formal security audits of AI systems. Therefore, the question reflects a stronger practice than the minimum requirements, leading to partial alignment.",
    
    "SE-4": "This question focuses on end-to-end security controls protecting the AI model during training, deployment and operation. ISO/IEC 42001 requires documentation of design and development, including security threats, and mandates structured deployment, operation and monitoring processes that account for trustworthiness concerns such as security. However, it does not prescribe concrete mechanisms such as encrypted artefacts, secure training environments or hardened deployment pipelines. Because the question focuses on those implementation specifics, the alignment is partial.",
    
    "SE-5": "This question asks about safeguards such as access restrictions, version control and integrity checks to prevent unauthorised model changes. ISO/IEC 42001 requires documenting AI system resources and considering AI-specific security threats, including tampering, but it does not explicitly require particular integrity-preservation controls. As the question reflects one way to address these risks rather than a stated requirement, the alignment is partial.",
    
    "SE-6": "This question focuses on specific protective measures against adversarial input manipulation and other attacks targeting model behaviour. ISO/IEC 42001 requires identification and management of AI-specific security threats and incorporation of those threats into lifecycle processes, but it does not mandate particular adversarial defence techniques. Because the question emphasises implementation-level defences that the standard leaves open, the alignment is partial.",
    
    "SE-7": "This question asks about concrete controls such as encryption or tokenisation to protect sensitive data handled in AI pipelines. ISO/IEC 42001 expects organisations to treat privacy and security as responsible-use objectives and to apply appropriate controls for processing PII, typically by reference to separate privacy and information security standards. It does not explicitly require specific techniques like encryption or tokenisation in the AI standard itself. As the question addresses implementation choices consistent with but not mandated by the control, the alignment is partial.",
    
    "SE-8": "This question evaluates whether the organisation conducts recurring vulnerability assessments and penetration tests specifically for AI systems. ISO/IEC 42001 requires security concerns to be managed throughout the AI lifecycle and testing and evaluation processes to be defined, but it does not explicitly mandate vulnerability scanning or penetration testing. Consequently, the question reflects a stronger assurance practice than the baseline standard, resulting in partial alignment.",
    
    "PR-1": "This question asks how the organisation ensures that AI-related processing complies with specific privacy laws in relevant jurisdictions. ISO/IEC 42001 requires organisations to define responsible-use objectives that include privacy and to clarify responsibilities for processing PII in accordance with applicable privacy requirements and reference privacy standards, but it does not address particular laws by name or prescribe jurisdiction-specific compliance processes. Because the question is more prescriptive about legal regimes than the standard, the alignment is partial.",
    
    "PR-2": "This question focuses on concrete privacy-preserving techniques such as anonymisation or pseudonymisation used to protect personal data throughout the AI lifecycle. ISO/IEC 42001 expects organisations to treat privacy as a responsible-use objective and to establish responsibilities and controls for PII processing, typically by adopting privacy-management standards, but it does not mandate particular techniques in the AI-specific text. As the question targets specific implementation choices consistent with, but not explicitly required by, the standard, the alignment is partial.",
    
    "PR-3": "This question examines mechanisms for obtaining, recording and managing user consent for data collection and processing in AI systems. ISO/IEC 42001 highlights privacy as a key responsible-use objective and requires that responsibilities for processing PII reflect applicable privacy requirements, which generally include lawful-basis concepts such as consent. However, it does not describe consent workflows, logging mechanisms or consent management explicitly. Because the question is more detailed than the standard in this area, the alignment is partial.",
    
    "PR-4": "This question asks how the organisation enforces purpose limitation, preventing personal data from being reused in ways inconsistent with its original purpose. ISO/IEC 42001 expects organisations to align PII processing responsibilities with applicable privacy requirements, which typically include purpose-limitation principles, but the standard does not specify mechanisms such as purpose-based access controls or data-use tagging. As the question concentrates on practical enforcement mechanisms not explicitly described in the AI standard, the alignment is partial.",
    
    "PR-5": "This question explores whether the organisation systematically evaluates how well privacy controls work and how they interact with model performance, including trade-offs between privacy and utility. ISO/IEC 42001 requires organisations to define responsible-use objectives that include privacy alongside reliability and security and to manage trustworthiness concerns across the AI lifecycle, suggesting that multiple objectives must be balanced. Nevertheless, it does not explicitly require quantitative analysis of privacy controls versus performance. As such, the alignment is partial.",
    
    "PR-6": "This question asks how the organisation monitors AI systems in operation to detect and prevent privacy violations such as misuse or leakage of personal data. ISO/IEC 42001 requires organisations to manage privacy and security concerns across the lifecycle and to define elements for ongoing operation and monitoring, including performance monitoring and support, but it does not specify particular privacy-monitoring controls or alerting mechanisms. Because the question focuses on operational techniques beyond what the standard explicitly describes, the alignment is partial.",
    
    "PR-7": "This question requires explicit evaluation of privacy risks at both development and deployment stages of the AI system lifecycle. ISO/IEC 42001 mandates that trustworthiness concerns, including privacy, be managed across the lifecycle and that responsibilities and controls for PII processing be aligned with privacy frameworks, which supports multi-stage risk consideration. However, it does not specifically call out separate development- and deployment-phase privacy risk assessments. Therefore, the alignment is partial.",
    
    "PR-8": "This question focuses on how the organisation ensures that personal data used by AI systems remains compliant with data-protection requirements when moved across jurisdictions. ISO/IEC 42001 expects organisations to treat privacy as a responsible-use objective and to define responsibilities and controls for PII processing in line with applicable privacy requirements and reference standards, but it does not explicitly mention cross-border transfers or localisation obligations in the AI-specific guidance. As a result, the alignment is partial.",
    
    "SA-1": "This question asks whether a structured safety impact assessment has been carried out for the AI system. ISO/IEC 42001 requires organisations to manage AI-system trustworthiness, including safety, throughout the lifecycle and to define testing, evaluation and validation steps, but it does not explicitly mandate a dedicated safety impact assessment artefact. The question reflects a stronger practice aligned with the intent of the standard but not explicitly required, so the alignment is partial.",
    
    "SA-2": "This question explores safeguards that prevent unintended harmful outcomes, such as design constraints, human oversight or risk controls. ISO/IEC 42001 emphasises intended use, foreseeable misuse and safety as part of trustworthiness and requires testing and validation to ensure safe operation before deployment. However, it does not prescribe specific mechanisms such as override controls or safety envelopes. Because the question focuses on concrete safeguards beyond the standard's general requirements, the alignment is partial.",
    
    "SA-3": "This question asks whether real-time monitoring tools are in place to detect unsafe behaviour as the system operates. ISO/IEC 42001 requires ongoing operation and monitoring processes, including system monitoring and performance checks, but it does not explicitly require real-time or near real-time safety monitoring technologies. As the question is more specific than the control in this respect, the alignment is partial.",
    
    "SA-4": "This question seeks mechanisms to prioritise human safety when system actions conflict with safety requirements, such as human override, automatic shutdown or other control hierarchies. ISO/IEC 42001 recognises safety as a responsible-use objective and requires managing trustworthiness risks, but it does not prescribe explicit control-priority rules or override mechanisms. Because the question addresses detailed safety-handling strategies that go beyond the text of the standard, the alignment is partial.",
    
    "SA-5": "This question focuses on whether emergency shutdown or fail-stop procedures exist for situations where the AI system behaves unsafely. ISO/IEC 42001 requires organisations to plan deployment, validation, operation and monitoring to ensure safe functioning and to manage failures, but it does not explicitly require emergency shutdown protocols as a specific control. Therefore, the question is consistent with the underlying safety objectives but only partially aligned with explicit requirements.",
    
    "SA-6": "This question asks about structured identification and mitigation of risks or harms associated with the AI system. ISO/IEC 42001 requires organisations to manage trustworthiness risks, including safety, to evaluate foreseeable misuse and to define testing and validation steps. While these clauses support risk management conceptually, the standard does not provide a detailed methodology for hazard identification and mitigation. As a result, the alignment is partial.",
    
    "SA-7": "This question explores whether the system incorporates fail-safe mechanisms or redundancies so that unexpected behaviours do not lead to unsafe outcomes. ISO/IEC 42001 highlights robustness and safety as key objectives and requires lifecycle testing and monitoring but does not explicitly require redundant architectures or specific fail-safe designs. Because the question focuses on implementation patterns that go beyond the explicit text, the alignment is partial.",
    
    "SA-8": "This question asks about safety testing conducted in realistic or high-risk scenarios that mirror actual operating conditions. ISO/IEC 42001 requires testing, validation and evaluation that consider intended use and foreseeable misuse, which supports scenario-based safety testing conceptually, but it does not explicitly require testing in high-risk or stress-case environments. Accordingly, the alignment is partial.",
    
    "IN-1": "This question requires the organisation to implement measures to make the AI system accessible and usable for diverse users, including those with disabilities and underserved communities. ISO/IEC 42001 requires organisations to define responsible-use objectives that can include accessibility, usability and inclusiveness and to consider affected individuals and user needs during design. However, it does not prescribe specific accessibility techniques or detailed guidelines. Therefore, the question is aligned with the intent but more prescriptive, leading to partial alignment.",
    
    "IN-2": "This question examines whether diverse stakeholder perspectives were explicitly sought and integrated during design and development. ISO/IEC 42001 requires identification of affected individuals and stakeholders and engagement with them to understand impacts and expectations, which conceptually supports including a range of perspectives. The standard does not explicitly require diversity criteria (such as culture or gender) in stakeholder selection, so the alignment is partial.",
    
    "IN-3": "This question asks whether the organisation conducts audits to identify exclusionary outcomes or unintended impacts on particular user groups. ISO/IEC 42001 requires evaluating impacts on individuals and groups, considering foreseeable misuse and managing trustworthiness risks, which supports ongoing assessment of adverse impacts. However, it does not explicitly require named fairness or exclusion audits. Thus, the question is consistent with the intent but only partially aligned with explicit requirements.",
    
    "IN-4": "This question focuses on how accessibility requirements for users with disabilities are incorporated into system design and implementation. ISO/IEC 42001 identifies accessibility, usability and inclusiveness as potential responsible-use objectives and requires that human factors and accessibility be addressed in design, but it does not reference specific accessibility standards or detailed technical requirements. Because the question targets practical implementation choices that go beyond the standard's general expectations, the alignment is partial.",
    
    "IN-5": "This question asks whether stakeholders from diverse demographic backgrounds participate in design and testing activities. ISO/IEC 42001 requires identifying stakeholders and affected individuals and engaging with them, but it does not specify demographic diversity or representation thresholds for those participants. The question reflects a stronger practice than explicitly required by the standard, leading to partial alignment.",
    
    "IN-6": "This question explores specific measures taken to ensure the AI system meets the needs of underrepresented or marginalised communities. ISO/IEC 42001 requires consideration of impacts on individuals and groups and promotes accessible and inclusive design as part of responsible-use objectives, but it does not explicitly call out underrepresented communities or mandate equity-focused functionality. As such, the alignment is partial.",
    
    "IN-7": "This question examines whether the system accounts for language, cultural and regional differences in its design. ISO/IEC 42001 supports understanding affected groups, user needs and human factors in system design, which can encompass these aspects, but it does not explicitly require localisation or multi-language support. Because the question addresses specific inclusivity practices that extend beyond the explicit text, the alignment is partial.",
    
    "IN-8": "This question asks how the organisation evaluates system performance across user groups to detect unintentional exclusion. ISO/IEC 42001 requires evaluating impacts on individuals and groups, monitoring system performance and managing trustworthiness concerns across the lifecycle, which supports assessing exclusion risks conceptually. However, it does not explicitly mandate demographic segmentation or exclusion testing, so the alignment is partial.",
    
    "SU-1": "This question requires the organisation to assess the environmental impact of training and deploying its AI system, ideally using metrics such as energy use or carbon footprint. ISO/IEC 42001 expects organisations to consider environmental sustainability as part of societal impacts and notes that AI workloads can have significant environmental effects, but it does not explicitly mandate quantitative measurement of energy use or emissions per system. Because the question goes further than the explicit requirement by asking for concrete impact assessment, the alignment is partial.",
    
    "SU-2": "This question focuses on whether the organisation actively looks for algorithmic efficiency improvements to reduce computational load. ISO/IEC 42001 requires documentation of tooling resources, including optimisation methods, and identification of system and computing resource needs, which conceptually supports efficiency considerations but does not explicitly require exploring algorithmic optimisation for sustainability purposes. As a result, the alignment is partial.",
    
    "SU-3": "This question asks whether cloud or infrastructure choices are made with a preference for renewable energy. ISO/IEC 42001 directs organisations to consider climate change and environmental impacts as part of their context and to treat environmental sustainability as a societal impact of AI, but it does not explicitly require choosing providers based on renewable energy use. Because the question captures a specific design choice aligned with sustainability goals but not mandated by the standard, the alignment is partial.",
    
    "SU-4": "This question requires estimation of the AI system's carbon footprint across training and deployment. ISO/IEC 42001 highlights environmental sustainability as a key impact area and notes that AI can contribute to greenhouse gas emissions, supporting the need to understand environmental effects. However, it does not explicitly require per-system carbon-footprint estimates. Thus, the question is consistent with the intent but only partially aligned with explicit requirements.",
    
    "SU-5": "This question asks whether algorithms have been specifically optimised to reduce computational resource consumption. ISO/IEC 42001 requires organisations to document tooling resources and understand system and computing resource requirements, and it acknowledges that AI workloads can be resource-intensive with environmental impact. Nonetheless, it does not explicitly require algorithmic optimisation to minimise resource use as a sustainability measure. Therefore, the alignment is partial.",
    
    "SU-6": "This question focuses on selecting hardware or cloud platforms based on energy efficiency characteristics. ISO/IEC 42001 requires documentation of system and computing resources and notes that organisations should consider the environmental impact of hardware used to run AI workloads, including manufacturing and operation. While this supports factoring energy efficiency into decisions, the standard stops short of mandating that only energy-efficient platforms be used. As a result, the alignment is partial.",
    
    "SU-7": "This question explores how the organisation explicitly balances environmental sustainability goals with performance requirements when designing and operating AI systems. ISO/IEC 42001 notes that AI development and use can significantly affect environmental sustainability and that organisations should consider these impacts alongside other objectives, including safety, but it does not describe specific trade-off frameworks or decision criteria. Because the question focuses on an explicit balancing process that is implied but not detailed in the standard, the alignment is partial.",
    
    "SU-8": "This question asks whether the organisation monitors and tracks environmental impact metrics for AI systems on an ongoing basis. ISO/IEC 42001 requires monitoring, measurement, analysis and evaluation of the AI management system's performance and emphasises environmental sustainability as a relevant impact area, which supports ongoing consideration of environmental effects. However, it does not explicitly require longitudinal tracking of specific environmental metrics for each AI system. Thus, the alignment is partial.",
}

print("Loading existing ISO 42001 alignment data...")
with open('/app/frontend/src/data/iso42001AlignmentData.json', 'r') as f:
    data = json.load(f)

print(f"Current questions in database: {len(data)}")
print("\nUpdating ONLY alignmentRationale field for all questions...")
print("=" * 70)

updated_count = 0
for question_code, new_rationale in updated_rationales.items():
    if question_code in data:
        # Update ONLY the alignmentRationale field
        # Preserve existing citation and controlIntent
        data[question_code]['alignmentRationale'] = new_rationale
        updated_count += 1
        print(f"✅ {question_code}")
    else:
        print(f"⚠️  {question_code} not found in database")

print("\n" + "=" * 70)
print(f"✅ Updated {updated_count} questions")

# Save the updated data
with open('/app/frontend/src/data/iso42001AlignmentData.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("✅ File saved successfully")

# Verify that citation and controlIntent are preserved
print("\n" + "=" * 70)
print("Verification - Checking field preservation...")
sample_codes = ['FA-1', 'TR-1', 'SE-1']
for code in sample_codes:
    if code in data:
        has_all_fields = all(k in data[code] for k in ['alignmentRationale', 'citation', 'controlIntent'])
        print(f"{code}: All fields present: {'✅' if has_all_fields else '❌'}")

questions_with_all_fields = sum(1 for q in data.values() 
                                 if all(k in q for k in ['alignmentRationale', 'citation', 'controlIntent']))
print(f"\n📊 Questions with all 3 fields: {questions_with_all_fields}/{len(data)}")
print("✅ Update complete!")
