#!/usr/bin/env python3
"""
Create a working DOCX template for AM AI SAFE reports
"""

from docx import Document
from docx.shared import Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os

def create_am_ai_safe_template():
    """Create a proper AM AI SAFE report template"""
    doc = Document()
    
    # Title
    title = doc.add_heading('AM AI SAFE Assessment Report', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Organization info
    doc.add_heading('Organization Information', level=1)
    org_table = doc.add_table(rows=3, cols=2)
    org_table.style = 'Table Grid'
    
    org_table.cell(0, 0).text = 'Organization:'
    org_table.cell(0, 1).text = '{{org.name}}'
    org_table.cell(1, 0).text = 'Assessment Date:'
    org_table.cell(1, 1).text = '{{assessment.date}}'
    org_table.cell(2, 0).text = 'Report Version:'
    org_table.cell(2, 1).text = '{{assessment.version}}'
    
    # Executive Summary
    doc.add_heading('Executive Summary', level=1)
    doc.add_paragraph('Overall AI Maturity Score: {{overall.score}}%')
    doc.add_paragraph('Maturity Tier: {{overall.tier}}')
    
    # Assessment Heatmap
    doc.add_heading('Assessment Heatmap', level=1)
    doc.add_paragraph('The following heatmap visualizes your organization\'s AI maturity across all domains:')
    
    # Placeholder for heatmap image
    heatmap_para = doc.add_paragraph()
    heatmap_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    # The heatmap image will be inserted here: {{heatmap_image}}
    doc.add_paragraph('{{heatmap_image}}')
    
    # High Priority Actions
    doc.add_heading('High Priority Actions', level=1)
    doc.add_paragraph('The following actions require immediate attention:')
    
    # Use proper Jinja2 syntax for loops
    doc.add_paragraph('{% for action in actions.high %}')
    doc.add_paragraph('• {{action.text}} ({{action.domain}})')
    doc.add_paragraph('{% endfor %}')
    
    # Medium Priority Actions
    doc.add_heading('Medium Priority Actions', level=1)
    doc.add_paragraph('The following actions should be addressed in the medium term:')
    
    doc.add_paragraph('{% for action in actions.medium %}')
    doc.add_paragraph('• {{action.text}} ({{action.domain}})')
    doc.add_paragraph('{% endfor %}')
    
    # Low Priority Actions
    doc.add_heading('Low Priority Actions', level=1)
    doc.add_paragraph('The following actions can be addressed as resources allow:')
    
    doc.add_paragraph('{% for action in actions.low %}')
    doc.add_paragraph('• {{action.text}} ({{action.domain}})')
    doc.add_paragraph('{% endfor %}')
    
    # Footer
    doc.add_page_break()
    doc.add_paragraph('This report was generated by the AM AI SAFE assessment platform.')
    doc.add_paragraph('For more information, visit: https://vciso.one')
    
    # Save template
    template_path = '/app/backend/templates/docx/AM_AI_SAFE_Report_TEMPLATE.docx'
    doc.save(template_path)
    print(f"✅ Created working template at: {template_path}")
    return template_path

if __name__ == "__main__":
    create_am_ai_safe_template()